name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true

    - name: Upgrade intl dependency
      run: flutter pub add intl:^0.20.2

    - name: Install flutter dependencies
      run: flutter pub get

    - name: Install Rust Tools & Generate Bridge Code
      shell: pwsh
      run: |
        cargo install flutter_rust_bridge_codegen --version 2.0.0-dev.43
        cargo install cargo-bundle-licenses
        # Add Path and Generate Bridge Code
        & "$($env:USERPROFILE)\.cargo\bin\flutter_rust_bridge_codegen.exe" generate

    - name: Build Windows desktop app
      run: flutter build windows --release
      
    - name: Package release artifacts
      run: Compress-Archive -Path build/windows/runner/Release -DestinationPath windows-app.zip

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: windows-app.zip
